### ISSUE TITLE
Wishlist: Preserve timestamps of source files

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/RAWcooked#205] opened 2019-03-27 18:05 UTC
Would be nice if the original timestamps of the source files could be preserved and restored when unpacking.

:cake:

**Comment by JeromeMartinez** [comment] 2019-03-27 18:30
Duplicate of https://github.com/MediaArea/RAWcooked/issues/141.

**Closed by JeromeMartinez** 2019-03-27 18:30 UTC
Labels: duplicate
