### ISSUE TITLE
crash when using `-level 1`

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#104] opened 2018-06-08 15:47 UTC
When using the option `-level 1` on regular RGB48 content, I receive an error:

<img width="890" alt="bildschirmfoto 2018-06-08 um 17 46 34" src="https://user-images.githubusercontent.com/3246607/41167706-03f1b890-6b44-11e8-9913-6f6710a8ad9a.png">

**Comment by JeromeMartinez** [comment] 2018-06-08 16:32
duplicate of https://github.com/MediaArea/RAWcooked/issues/103 (same source of the issue).

**Closed by JeromeMartinez** 2018-06-08 16:32 UTC
